public class AppConfig {
    private AppConfig(){} //CRIACAO DE UM CONSTRUTOR PRIVADO, PARA QUE SOBRESCREVA O CONSTRUTOR DEFAULT

    private static class AppConfigSyncronize{ //CRIA-SE UMA CLASSE INTERMEDIARIA QUE POSSUA UMA INSTANCIA DE APPCONFIG
        public static final AppConfig appConfig = new AppConfig(); //GERA UMA INSTANCIA DA CLASSE PRINCIPAI AQUI DENTRO, COMO A CLASSE É PRIVADA NESSE ESCOPO, O ATRIBUTO PODE SER PUBLICO
    }

    public static AppConfig initialize(){ //SE GERA UM METODO INITIALIZE POR EXEPLO, QUE RETORNE UMA INSTANCIA DESSA CLASSE
        return AppConfigSyncronize.appConfig; //AQUI, EU CHAMO MINHA CLASSE PRIVADA
    }

    //O MOTIVO DAS 2 CLASSES NESSE ESCOPO É SIMPLES, É O CONTEXTO DE LAZY INITIAALIZATION, ISSO GARANTE QUE A JVM
    //SO CRIE A INSTANCIA DESSA CLASSE CASO REALMENTE SEJA CHAMADA, POIS ELA VAI CRIAR O CONSTRUTOR PRIVADO DO APPCONFIG, MAS NAO A INSTNACIA DA MESMA
    //FORA ESSA CLASSE, ELA SEGUE OS OUTROS PADROES DO SINGLETON, QUE UMA CLASSE QUE POSSUI CONFIGURACOES POR EXEMPLO, DEVERIA TER
}
